// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SAO": DraftSubmitTrx Resource Client
//
// Command:
// $ go generate

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetDraftSubmitTrxPath computes a request path to the get action of DraftSubmitTrx.
func GetDraftSubmitTrxPath(trxID string) string {
	param0 := trxID

	return fmt.Sprintf("/sao/v1/draft-submit-transaction/%s", param0)
}

// Get submitted draft transaction metadata for the given ID
func (c *Client) GetDraftSubmitTrx(ctx context.Context, path string, trxD *int) (*http.Response, error) {
	req, err := c.NewGetDraftSubmitTrxRequest(ctx, path, trxD)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetDraftSubmitTrxRequest create the request corresponding to the get action endpoint of the DraftSubmitTrx resource.
func (c *Client) NewGetDraftSubmitTrxRequest(ctx context.Context, path string, trxD *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if trxD != nil {
		tmp38 := strconv.Itoa(*trxD)
		values.Set("trxD", tmp38)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
