// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SAO": draft Resource Client
//
// Command:
// $ go generate

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetDraftPath computes a request path to the get action of draft.
func GetDraftPath(draftID int) string {
	param0 := strconv.Itoa(draftID)

	return fmt.Sprintf("/sao/v1/drafts/%s", param0)
}

// Get the complete Entry Draft metadata (excluding the associated sources) for the given ID
func (c *Client) GetDraft(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetDraftRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetDraftRequest create the request corresponding to the get action endpoint of the draft resource.
func (c *Client) NewGetDraftRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowDraftPath computes a request path to the show action of draft.
func ShowDraftPath() string {

	return fmt.Sprintf("/sao/v1/drafts/")
}

// List the entry drafts without their sources.
func (c *Client) ShowDraft(ctx context.Context, path string, contest *int, contestSlug *string, page *int, pageSize *int, sort *string, task *int, taskSlug *string, user *int) (*http.Response, error) {
	req, err := c.NewShowDraftRequest(ctx, path, contest, contestSlug, page, pageSize, sort, task, taskSlug, user)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowDraftRequest create the request corresponding to the show action endpoint of the draft resource.
func (c *Client) NewShowDraftRequest(ctx context.Context, path string, contest *int, contestSlug *string, page *int, pageSize *int, sort *string, task *int, taskSlug *string, user *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if contest != nil {
		tmp45 := strconv.Itoa(*contest)
		values.Set("contest", tmp45)
	}
	if contestSlug != nil {
		values.Set("contest_slug", *contestSlug)
	}
	if page != nil {
		tmp46 := strconv.Itoa(*page)
		values.Set("page", tmp46)
	}
	if pageSize != nil {
		tmp47 := strconv.Itoa(*pageSize)
		values.Set("page_size", tmp47)
	}
	if sort != nil {
		values.Set("sort", *sort)
	}
	if task != nil {
		tmp48 := strconv.Itoa(*task)
		values.Set("task", tmp48)
	}
	if taskSlug != nil {
		values.Set("task_slug", *taskSlug)
	}
	if user != nil {
		tmp49 := strconv.Itoa(*user)
		values.Set("user", tmp49)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
