// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SAO": entry Resource Client
//
// Command:
// $ go generate

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetEntryPath computes a request path to the get action of entry.
func GetEntryPath(entryID int) string {
	param0 := strconv.Itoa(entryID)

	return fmt.Sprintf("/sao/v1/entries/%s", param0)
}

// Get the complete entry metadata (excluding the associated sources) for the given ID
func (c *Client) GetEntry(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetEntryRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetEntryRequest create the request corresponding to the get action endpoint of the entry resource.
func (c *Client) NewGetEntryRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowEntryPath computes a request path to the show action of entry.
func ShowEntryPath() string {

	return fmt.Sprintf("/sao/v1/entries/")
}

// List the ranked entries without their sources.
func (c *Client) ShowEntry(ctx context.Context, path string, contest *int, contestSlug *string, page *int, pageSize *int, sort *string, task *int, taskSlug *string, user *int) (*http.Response, error) {
	req, err := c.NewShowEntryRequest(ctx, path, contest, contestSlug, page, pageSize, sort, task, taskSlug, user)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowEntryRequest create the request corresponding to the show action endpoint of the entry resource.
func (c *Client) NewShowEntryRequest(ctx context.Context, path string, contest *int, contestSlug *string, page *int, pageSize *int, sort *string, task *int, taskSlug *string, user *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if contest != nil {
		tmp56 := strconv.Itoa(*contest)
		values.Set("contest", tmp56)
	}
	if contestSlug != nil {
		values.Set("contest_slug", *contestSlug)
	}
	if page != nil {
		tmp57 := strconv.Itoa(*page)
		values.Set("page", tmp57)
	}
	if pageSize != nil {
		tmp58 := strconv.Itoa(*pageSize)
		values.Set("page_size", tmp58)
	}
	if sort != nil {
		values.Set("sort", *sort)
	}
	if task != nil {
		tmp59 := strconv.Itoa(*task)
		values.Set("task", tmp59)
	}
	if taskSlug != nil {
		values.Set("task_slug", *taskSlug)
	}
	if user != nil {
		tmp60 := strconv.Itoa(*user)
		values.Set("user", tmp60)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
