// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "SAO v1": scores Resource Client
//
// Command:
// $ goagen
// --design=github.com/jossemargt/cms-sao/design
// --force=true
// --notool=true
// --out=$(GOPATH)/src/github.com/jossemargt/cms-sao
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// GetScoresPath computes a request path to the get action of scores.
func GetScoresPath(scoreID string) string {
	param0 := scoreID

	return fmt.Sprintf("/sao/v1/scores/%s", param0)
}

// Returns an specific score with the given entry and testcase ID
func (c *Client) GetScores(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetScoresRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetScoresRequest create the request corresponding to the get action endpoint of the scores resource.
func (c *Client) NewGetScoresRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowScoresPath computes a request path to the show action of scores.
func ShowScoresPath() string {

	return fmt.Sprintf("/sao/v1/scores/")
}

// List all the scores delimited by the query params
func (c *Client) ShowScores(ctx context.Context, path string, contest *int, entry *int, page *int, pageSize *int, sort *string, task *int, user *int) (*http.Response, error) {
	req, err := c.NewShowScoresRequest(ctx, path, contest, entry, page, pageSize, sort, task, user)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowScoresRequest create the request corresponding to the show action endpoint of the scores resource.
func (c *Client) NewShowScoresRequest(ctx context.Context, path string, contest *int, entry *int, page *int, pageSize *int, sort *string, task *int, user *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if contest != nil {
		tmp9 := strconv.Itoa(*contest)
		values.Set("contest", tmp9)
	}
	if entry != nil {
		tmp10 := strconv.Itoa(*entry)
		values.Set("entry", tmp10)
	}
	if page != nil {
		tmp11 := strconv.Itoa(*page)
		values.Set("page", tmp11)
	}
	if pageSize != nil {
		tmp12 := strconv.Itoa(*pageSize)
		values.Set("page_size", tmp12)
	}
	if sort != nil {
		values.Set("sort", *sort)
	}
	if task != nil {
		tmp13 := strconv.Itoa(*task)
		values.Set("task", tmp13)
	}
	if user != nil {
		tmp14 := strconv.Itoa(*user)
		values.Set("user", tmp14)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
