// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "SAO v1": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/jossemargt/cms-sao/design
// --force=true
// --notool=true
// --out=$(GOPATH)/src/github.com/jossemargt/cms-sao
// --version=v1.3.1

package app

// EntryHref returns the resource href.
func EntryHref() string {
	return "/sao/v1/entries/"
}

// ResultHref returns the resource href.
func ResultHref() string {
	return "/sao/v1/results/"
}

// ScoresHref returns the resource href.
func ScoresHref() string {
	return "/sao/v1/scores/"
}
