// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SAO": Application Resource Href Factories
//
// Command:
// $ go generate

package app

// DraftHref returns the resource href.
func DraftHref() string {
	return "/sao/v1/drafts/"
}

// DraftresultHref returns the resource href.
func DraftresultHref() string {
	return "/sao/v1/draft-results/"
}

// EntryHref returns the resource href.
func EntryHref() string {
	return "/sao/v1/entries/"
}

// ResultHref returns the resource href.
func ResultHref() string {
	return "/sao/v1/results/"
}
